### PR TITLE
Image reader

### LINKED ISSUE #59: Xray_image_reader
This issue is created to add an x-ray image reader for the x-ray classification task.

this feature will read an image from a given path and add it to datapack

### PR DESCRIPTION
**Pull request by bhaskar2443053**
This PR fixes #59  

### Description of changes
This a new x-ray image reader built for image classification task 

### Possible influences of this PR.
this reader needs forte 0.3.0.dev2 version to support image payload.

### Test Conducted
Describe what test cases are included for the PR.

### CODE REVIEW

File: fortex/health/readers/xray_image_reader.py [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+    def _collect(self, image_path) -> Iterator[Any]:
+        r"""Should be called with param ``image_path`` which is a path to
+        the Image file.
+
+        Args:
+            image_path: path to the Image file.
+
+        Returns: Image path
+        """
+        return image_path
```
Comment (Piyush13y) [inline fortex/health/readers/xray_image_reader.py:43]: I am not sure if you have gone through [audio_reader.py](https://github.com/asyml/forte/blob/master/forte/data/readers/audio_reader.py) or if we specifically want something like the current implementation, but we can implement our X-ray image reader in a similar manner as the linked file, supporting reading multiple images with the same instance of `XrayImageReader`.

File: fortex/health/readers/xray_image_reader.py [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+
+    def _parse_pack(self, file_path: str) -> Iterator[DataPack]:
+        pack: DataPack = DataPack()
+
+        # Read in image data and store in DataPack
+        img = self.Image.open(file_path)
+        # coverts the image into RBG if we receive a grayscale image
+        if img.mode == "L":
+            img = img.convert("RGB")
+        pack.add_image(image=np.array(img))
```
Comment (Piyush13y) [inline fortex/health/readers/xray_image_reader.py:53]: Minor nitpick: Lets have spaces around all operators for consistency and readability. 
```suggestion
        pack.add_image(image = np.array(img))
```

File: fortex/health/readers/xray_image_reader.py [hunk 3]
```diff
@@ -0,0 +1,56 @@
+# Copyright 2021 The Forte Authors. All Rights Reserved.
```
Comment (Piyush13y) [inline fortex/health/readers/xray_image_reader.py:1]:
```suggestion
# Copyright 2022 The Forte Authors. All Rights Reserved.
```

File: tests/fortex/health/readers/xray_image_reader_test.py [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+"""
+Unit tests for XrayImageReader
+"""
+import sys
+
+sys.path.insert(0, "../../../../")
```
Comment (Piyush13y) [inline tests/fortex/health/readers/xray_image_reader_test.py:19]: I am not sure if I correctly understand necessity of this here, is there a module that is inaccessible without this in this file?

File: fortex/health/readers/xray_image_reader.py (hunk 1 above)
Comment (bhaskar2443053) [reply fortex/health/readers/xray_image_reader.py:43]: I have gone through it.
you mean reading a directory of images right?

File: tests/fortex/health/readers/xray_image_reader_test.py (hunk 4 above)
Comment (bhaskar2443053) [reply tests/fortex/health/readers/xray_image_reader_test.py:19]: yes without this, I was unable to import the module.

File: fortex/health/readers/xray_image_reader.py (hunk 1 above)
Comment (bhaskar2443053) [reply fortex/health/readers/xray_image_reader.py:44]: I have added a reader for reading a folder of image files.

Comment (bhaskar2443053) [reply fortex/health/readers/xray_image_reader.py:44]: I have added a reader for reading a folder of image files.

**Comment by bhaskar2443053** [comment]
@Piyush13y 
flake8 is throwing an error 
eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'

with reference to https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean
I tried to downgrade importlib_metadata and retest. But, It still shows the same error.

any suggestions?

**Comment by Piyush13y** [comment]
> @Piyush13y flake8 is throwing an error eps = importlib_metadata.entry_points().get(self.namespace, ()) AttributeError: 'EntryPoints' object has no attribute 'get'
> 
> with reference to
> 
> 1. https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean
> 2. [Breaking change in 7e5bae4 (importlib_metadata 5) python/importlib_metadata#409](https://github.com/python/importlib_metadata/issues/409)
>    I tried to downgrade importlib_metadata and retest. But, It still shows the same error.
> 
> any suggestions?

@bhaskar2443053 If you look at the logs, it says we are still installing importlib-metadata-5.0 and not a deprecated version of it. That's why you see the same error.

**Comment by bhaskar2443053** [comment]
> > @Piyush13y flake8 is throwing an error eps = importlib_metadata.entry_points().get(self.namespace, ()) AttributeError: 'EntryPoints' object has no attribute 'get'
> > with reference to
> > 
> > 1. https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean
> > 2. [Breaking change in 7e5bae4 (importlib_metadata 5) python/importlib_metadata#409](https://github.com/python/importlib_metadata/issues/409)
> >    I tried to downgrade importlib_metadata and retest. But, It still shows the same error.
> > 
> > any suggestions?
> 
> @bhaskar2443053 If you look at the logs pertaining to your commits where you change the version in the setup file, it says we are still installing `importlib-metadata-5.0` and not a deprecated version of it (<5.0.0). That's why you still see the same error when you downgraded the library.
> 
> Try adding `importlib-metadata<5.0.0` in `main.yml` right before we install `flake8` in the 'Install Dependencies' section, and see if that works.

Hi @Piyush13y I tried out your suggestion, but it gives a new error.

image

I also tried fast-deps, but this is also failing cl jobs.

**Comment by Piyush13y** [comment]
> > > @Piyush13y flake8 is throwing an error eps = importlib_metadata.entry_points().get(self.namespace, ()) AttributeError: 'EntryPoints' object has no attribute 'get'
> > > with reference to
> > > 
> > > 1. https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean
> > > 2. [Breaking change in 7e5bae4 (importlib_metadata 5) python/importlib_metadata#409](https://github.com/python/importlib_metadata/issues/409)
> > >    I tried to downgrade importlib_metadata and retest. But, It still shows the same error.
> > > 
> > > any suggestions?
> > 
> > 
> > @bhaskar2443053 If you look at the logs pertaining to your commits where you change the version in the setup file, it says we are still installing `importlib-metadata-5.0` and not a deprecated version of it (<5.0.0). That's why you still see the same error when you downgraded the library.
> > Try adding `importlib-metadata<5.0.0` in `main.yml` right before we install `flake8` in the 'Install Dependencies' section, and see if that works.
> 
> Hi @Piyush13y I tried out your suggestion, but it gives a new error.
> 
> image
> 
> I also tried fast-deps, but this is also failing cl jobs.

So, when you use a downgraded version of importlib-metadata, its not failing with flake8 anymore. Its failing due to a version conflict while installing requirements for test.

**Comment by Piyush13y** [comment]
@bhaskar2443053 On downgrading the importlib-metadata library, flake8 was working fine. I have removed the redundant resolver from test installation too now. You can look at the issues in the pipeline checks now, should be resolvable. Let me know if you face any other issues.

**Comment by bhaskar2443053** [comment]
> @bhaskar2443053 On downgrading the importlib-metadata library, flake8 was working fine. I have removed the redundant resolver from test installation too now. You can look at the issues in the pipeline checks now, should be resolvable. Let me know if you face any other issues.

great the importlib-metadata issue is solved. I also resolved the type ignore issue from reader. Now all cl has passed.
please review the PR again, and let me know if anything needs to be changed.

File: fortex/health/readers/xray_image_reader.py [hunk 5]
```diff
@@ -0,0 +1,109 @@
...
+        # coverts the image into RBG if we receive a grayscale image
+        if img.mode == "L":
+            img = img.convert("RGB")
+        pack.add_image(image=np.array(img))
+        pack.pack_name = file_path
+
+        yield pack
+
+
+class XrayImageReaderDir(PackReader):
```
Comment (Piyush13y) [inline fortex/health/readers/xray_image_reader.py:60]: I don't think we need a different class altogether to support reading multiple images from a directory, its almost completely redundant. We can just have one class and it will support both reading a single image and multiple images from a directory just like `audio_reader.py` does. Essentially, you can just have the `XrayImageReaderDir` class to support both scenarios. Also, just one test file should suffice, you can have multiple tests within it, if need be.

File: tests/fortex/health/readers/xray_image_reader_test.py (hunk 4 above)
Comment (Piyush13y) [reply tests/fortex/health/readers/xray_image_reader_test.py:19]: Oh alright, which  module import fails without this?

Comment (bhaskar2443053) [reply tests/fortex/health/readers/xray_image_reader_test.py]: XrayImageReaderDir itself is unable to import from the examples folder.

File: fortex/health/readers/xray_image_reader.py (hunk 5 above)
Comment (bhaskar2443053) [reply fortex/health/readers/xray_image_reader.py]: done.

File: tests/fortex/health/readers/xray_image_reader_test.py (hunk 4 above)
Comment (Piyush13y) [reply tests/fortex/health/readers/xray_image_reader_test.py]: I am a little apprehensive of this line, as future processors/reader writers would refer existing processors/readers as a template and this doesn't seem like the best way to import data samples from `/example`s folder. Trying out a change, will merge this PR once that works.

**Review by Piyush13y — APPROVED** [review]
